/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.social.login.demo.app.presentations.controller;

import com.example.social.login.demo.app.presentations.controller.model.User;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-04-09T01:22:41.242558+09:00[Asia/Tokyo]")
@Validated
@Tag(name = "User", description = "the User API")
public interface ApiApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /api/birthstone : BirthStone API
     * 誕生石情報を取得します
     *
     * @param userId ユーザーID (required)
     * @return 200 (OK) (status code 200)
     *         or 400 (Bad Request) (status code 400)
     */
    @Operation(
        operationId = "getBirthstone",
        summary = "BirthStone API",
        description = "誕生石情報を取得します",
        tags = { "User" },
        responses = {
            @ApiResponse(responseCode = "200", description = "200 (OK)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = User.class))
            }),
            @ApiResponse(responseCode = "400", description = "400 (Bad Request)")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/birthstone",
        produces = { "application/json" }
    )
    default ResponseEntity<User> getBirthstone(
        @NotNull @Parameter(name = "user_id", description = "ユーザーID", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "user_id", required = true) Integer userId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"name\" : \"name\", \"id\" : 123 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
